bot:
  build: ./bot
  links:
    - db:mysql
  volumes:
    - /docker_storage/observe/status:/status
  container_name: bot.telegram

checker:
  build: ./checker
  links: 
    - db:mysql
  volumes:
    - /docker_storage/observe/checker:/checker
    - /docker_storage/observe/status:/status
  container_name: checker.telegram


db:
  restart: always
  build: ./db
  ports:
    - "127.0.0.1:8765:3306"
  environment:
    - TELEGRAM_API=335087225:AAHImO0Li0sGd9XbfGvX_2dfIdDWTF4Yb3w
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=observe
    - MYSQL_USER=observeUser
    - MYSQL_PASSWORD=observePassword
  volumes:
    - /docker_storage/observe/db:/var/lib/mysql
    - /docker_storage/observe/status:/status
    - ./db/init.dump/:/docker-entrypoint-initdb.d
  container_name: db.telegram